name: Print workflow
on: workflow_dispatch

jobs:

  print_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello
        run: echo "Hello world!"

  checkout_repo:
    needs: print_hello
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

  print_full_technical_info:
        needs: print_hello 
        runs-on: ubuntu-latest 
        steps:
        - name: Print full_tech_info
          run: sudo lshw

  print_short_technical_info:
    needs: print_full_technical_info 
    runs-on: ubuntu-latest 
    steps: 
      - name: Print short_tech_info 
        run: sudo lshw -short

